Team8-Open-Mind/OpenMind

src/components/ui/atoms/Button/Button.jsx
=> ✨ feat: PR 테스트 입니당

src/components/ui/molecules/card/link-card/Bookmark.jsx, src/components/ui/molecules/card/link-card/Bookmark.module.css, src/components/ui/molecules/card/link-card/CardCover.jsx, src/components/ui/molecules/card/link-card/CardImage.jsx, src/components/ui/molecules/card/link-card/CreatedAt.jsx, src/components/ui/molecules/card/link-card/Description.jsx, src/components/ui/molecules/card/link-card/KebabButton.jsx, src/components/ui/molecules/card/link-card/TimeElapsed.jsx, src/components/ui/molecules/card/link-card/context/CardProvider.jsx, src/components/ui/molecules/card/link-card/index.js, src/components/ui/molecules/modal/Modal.jsx, src/pages/test2-page/TestPage2.jsx
=> ✨ feat: sample file and folder 세팅

src/style/reset/reset.js
=> style : reset.css button 

src/components/ui/atoms/Button/Button.jsx, src/components/ui/atoms/Button/media-query.js
=> style/버튼 컴포넌트 반응형 빠진 부분 추가

src/components/ui/atoms/Button/Button.jsx
=> refactor/버튼에 onClickHandler 추가

src/components/ui/atoms/Button/Button.jsx, src/components/ui/atoms/Button/media-query.js
1. 버튼 높이 안맞는 부분 line-height 빠져서 그랬음 급수정하여 올림
=> 💄 style: button 컴포넌트 line-height 추가

src/components/ui/atoms/dropdown/DropdownHamburger.jsx, src/components/ui/atoms/dropdown/DropdownMenu.jsx, src/components/ui/atoms/dropdown/DropdownOption.jsx, src/components/ui/atoms/dropdown/DropdownSelect.jsx, src/components/ui/atoms/dropdown/arrow-dropdown/ArrowDropdown.jsx, src/components/ui/atoms/dropdown/context/DropdownProvider.jsx, src/components/ui/atoms/dropdown/hamburger-dropdown/HamburgerDropdown.jsx, src/components/ui/atoms/dropdown/index.js, src/hooks/useCloseModal.js, src/hooks/useModal.js, src/hooks/useMountedState.js, src/pages/list-page/ListPage.jsx
1. dropdown 컴포넌트를 추가하였습니다.(ArrowDropdown, HamburgerDropdown)
2. 스프라이트 아이콘 바뀐 사항에 맞춰서 변경하여 적용하였습니다.
Menu(ul 태그)에 position absolute를 줬더니 Option(li)컴포넌트의 크기와 position offset 조절이 쉽지 않네요. 나중에 스타일을 수정하덩가 해야겠습니다. (너무 어려운 cssㅠㅠ)
=> ✨ feat: dropdown 컴포넌트 추가, useModal 훅에 useCloseModal 훅 추가

src/components/ui/atoms/input/input-text-area/InputTextArea.jsx
1. isOverflowScroll 기본값 true 지정.
>
=> 🐛 fix: InputTextArea overflow scroll 될 수 있게 수정

src/components/ui/molecules/modal/ConfirmAlertModal.jsx, src/hooks/useConfirmAlert.jsx, src/pages/answer-page/AnswerPage.jsx, src/style/reset/reset.js
1. 알럿 다이알로그 (모달) 훅 -> 어차피 answer 페이지에서만 사용됨,,, 
2. 원래는 `ConfirmAlertModal.jsx`를 hook 안에 넣어주고 싶었으나 오류가 나서 일단 따로 넣어줌
흠흠
=> Feat/cofirm alert hook 권지민

src/components/ui/atoms/dropdown/context/DropdownProvider.jsx, src/components/ui/atoms/logo/Logo.jsx, src/hooks/useModal.js, src/pages/list-page/ListPage.jsx, src/style/global/GlobalStyle.jsx, src/style/reset/reset.js
=> Feature/link page 조형민

src/hooks/useSNSShare.js
useSNSShare javascript key 맞춰서 변경
>
env 파일 말씀드린대로 로컬에 잘 설정해 두시길 바랍니다.
=> 🧹 chore: useSNSShare javascript key 맞춰서 변경

src/components/ui/atoms/Button/floating-button/FloatingButton.jsx
기본값 true. 안 주려면 false를 수동으로 줘야 한다.
>
=> ✨ feat: FloatingButton boxShadow 추가 여부 선택할 수 있도록 변경

src/pages/answer-page/AnswerPage.jsx
1. 피드 카드 존재하지 않을 경우 문제 있을 수 있음
수정 전
수정 후
=> 💄 style: feed background 높이 수정

src/pages/answer-page/AnswerPage.jsx, src/pages/list-page/comp/list-contents/ListContents.jsx, src/pages/list-page/comp/list-contents/comp/no-lists/NoLists.jsx
1. NoList 컴포넌트 children 으로 텍스트 넘겨줄 수 있도록 수정
=> ♻️ refactor: NoList 컴포넌트 children 으로 텍스트 넘겨줄 수 있도록 수정

src/pages/list-page/comp/list-contents/ListContents.jsx
=> ✨ feat: NoLists 버튼기능 빠뜨린 거 추가

src/pages/list-page/comp/list-contents/comp/page-turner/PageTurnner.jsx
=> 🧹 chore: 좌우(<, >) 아이콘 감싸는 버튼을 호버 했을 때 아이콘 색 변경되도록 수정

src/components/ui/molecules/grid/GridItem.jsx, src/hooks/usePaginate.js, src/hooks/useResizeObserver.js, src/pages/list-page/comp/list-contents/ListContents.jsx, src/pages/list-page/comp/list-contents/comp/page-turner/PageTurnner.jsx
=> ♻️ refactor: usePaginate 리팩토링, GridItem 긴 이름 튀어나가는 거 막음.

src/api/answers/postAnswer.js, src/components/ui/atoms/Badge/BadgeBox.jsx, src/components/ui/atoms/ReplyTypeSwitch.jsx/ReplyTypeSwitch.jsx, src/components/ui/atoms/question-box/AnswerBox.jsx, src/components/ui/atoms/reply-type-box/ReplyTypeBox.jsx, src/components/ui/molecules/feed-card/FeedCard.jsx, src/components/ui/molecules/feed-card/FeedCardContainer.jsx, src/hooks/useAsync.js, src/hooks/useAsyncOnMount.js, src/pages/answer-page/AnswerPage.jsx, src/pages/list-page/comp/list-contents/ListContents.jsx, src/pages/main-page/MainPage.jsx
1. useAsync/useAsyncOnMount return 내보낼때 객체로 수정하였음 (전체 파일 살펴보면서 import 된것 수정하였으나 누락된 부분이 있을 수 있으니.. 참고 부탁드립니다..)
2. post는 보내지는데!! 새로고침 해야 반영된 것 볼 수 있는거!!! 그니까 리렌더링 안되는 부분 !!! 수정 완료!!! (갓형민 갓useToggle)
=> Feat/답변 보내기 post는 되지만 리렌더링 안되는 부분 수정 -권지민

src/api/questions/postReaction.js, src/components/ui/atoms/Reaction/Reaction.jsx, src/components/ui/atoms/question-box/AnswerBox.jsx, src/components/ui/molecules/feed-card/FeedCard.jsx
=> ✨ feat: 파워 드릴링으로 리액션 기능 추가

src/components/ui/atoms/dropdown/DropdownHamburger.jsx, src/components/ui/atoms/dropdown/DropdownSelect.jsx, src/components/ui/atoms/dropdown/context/DropdownProvider.jsx, src/components/ui/molecules/grid/GridContainer.jsx, src/hooks/usePaginate.js, src/pages/list-page/comp/list-contents/ListContents.jsx, src/pages/list-page/comp/list-contents/comp/grid-contents-area/GridContentsArea.jsx, src/pages/list-page/comp/list-contents/comp/grid-contents-area/hooks/useAppendNextPageCard.js, src/pages/list-page/comp/list-contents/comp/page-turner/PageTurnner.jsx
=> Feature/list page 조형민

src/pages/list-page/comp/list-contents/ListContents.jsx
useAsyncOnMount 디스트럭쳐링 맞춰서 코드 변경
>
=> 🧹 chore: useAsyncOnMount 디스트럭쳐링 맞춰서 코드 변경

src/api/answers/patchAnswer.js, src/api/answers/postAnswer.js, src/components/ui/atoms/ReplyTypeSwitch.jsx/ReplyTypeSwitch.jsx, src/components/ui/atoms/edit-type-box/EditTypeBox.jsx, src/components/ui/atoms/question-box/AnswerBox.jsx, src/components/ui/atoms/reject-reply/RejectReplyButton.jsx, src/components/ui/atoms/rejected-type-box/RejectedTypeBox.jsx, src/components/ui/atoms/reply-type-box/ReplyTypeBox.jsx, src/components/ui/molecules/feed-card/FeedCard.jsx, src/hooks/useConfirmAlert.jsx, src/pages/answer-page/AnswerPage.jsx, src/utils/card-type/feedCardType.js
=> Feat/거절, 수정 기능 추가 -권지민

src/components/ui/atoms/Badge/BadgeBox.jsx, src/components/ui/atoms/question-box/AnswerBox.jsx, src/components/ui/atoms/read-type-switch/ReadTypeSwitch.jsx, src/components/ui/molecules/feed-card/FeedCard.jsx, src/components/ui/molecules/feed-card/FeedCardContainer.jsx, src/hooks/useCheckAnswerPath.js, src/pages/not-found-page/NotFoundPage.jsx, src/utils/card-type/feedCardType.js
1. NotFoundPage 작업 
2. question 페이지에서 feedCard ui 다르게 나와야하는 부분 수정 (지금 feedCard쪽 푸시되어있지 않아 잘 되고있는지 확인이 어려운 상황임,,,)
- FeedCardContainer 안에서 path를 체크해서 ui 제어될 수 있도록하는 중인데 확인이 필요함
=> Feat/NotFound 및 

src/components/ui/atoms/question-box/AnswerBox.jsx
=> 💄 style: 피드카드 ui 깨지는 부분 급 수정

src/components/ui/molecules/nav-bar/NavBar.jsx
1. 로그인 된 상태일때 질문 하러가기 누르면 메인이 아니라 list로 이동하도록 (나도 로그인했지만 다른 사람한테 질문할 수 있어야 하니까)
=> 🧹 chore/navBar 링크 잘못된 것 수정

src/components/ui/atoms/question-box/AnswerBox.jsx
1. feedQuest 페이지에서 답변이 없는 경우 답변자의 프로필 이미지 및 닉네임이 보이지 않도록 한다.
=> refactor:/피드 카드 ui 별로 수정 추가

src/hooks/useCheckAuth.js
1. 정규 표현식으로 url 아이디값 가져오던 것을 useParam을 사용하여 쉽게 가져올 수 있도록 코드 변경
=> refactor/useParam으로 id url값 받아오기

src/components/ui/molecules/nav-bar/NavBar.jsx, src/hooks/useCheckAuth.js
1. 로그인된 상태가 아닌데 질문보러 가는 메뉴가 있는게 너무 어색함
2. 로그인된 상태가 아니면 로고만 보이도록 수정
=> refactor/navBar 메뉴 localStrage id 잇을때만 보이도록 변경

src/api/questions/postNewQuestion.js, src/components/ui/molecules/modal/AddQuestionModal.jsx, src/pages/list-page/comp/list-contents/comp/no-lists/NoLists.jsx, src/pages/main-page/MainPage.jsx, src/pages/question-feed-page/QuestFeedPage.jsx, src/style/breakpoints/mediaBreakpoints.js
=> feat: 모달기능 및 메인페이지 반응형 구현

package-lock.json, package.json
https://github.com/evanw/esbuild/issues/1646
참고
>
=> 🐛 fix: netlify esbuild 에러 추가하기 위한 의존성 추가

src/pages/question-feed-page/QuestFeedPage.jsx
=> chore/reaction 수정

src/components/ui/molecules/nav-bar/NavBar.jsx, src/hooks/useCheckAnswerPath.js
=> chore/수정했던게 빠져있어서 다시 추가

netlify.toml
netlify.toml 파일 redirect를 위해 추가
>
=> ✨ feat: netlify.toml 파일 redirect를 위해 추가

.eslintrc.cjs
=> 🧹 chore: eslint underscore(_) 붙이면 unused-var 에러 끄도록 설정

src/pages/question-feed-page/QuestFeedPage.jsx
=> fix: 토스트가 안나타나는 버그 수정

src/components/ui/molecules/feed-card/FeedCardContainer.jsx, src/hooks/useCloseModal.js, src/pages/main-page/MainPage.jsx
=> Feat/refactoring 권지민

src/components/ui/atoms/dropdown/DropdownOption.jsx, src/components/ui/atoms/dropdown/arrow-dropdown/ArrowDropdown.jsx, src/components/ui/atoms/dropdown/context/DropdownProvider.jsx, src/components/ui/atoms/dropdown/hamburger-dropdown/HamburgerDropdown.jsx, src/hooks/useAsyncFn_V2.js
=> Feature/drop down refactor 조형민

src/hooks/useAsync_V2.js, src/pages/answer-page/AnswerPage.jsx, src/pages/question-feed-page/QuestFeedPage.jsx
=> ♻️ refactor: useAsync_V2 enabled 옵션 추가

src/pages/answer-page/AnswerPage.jsx
=> Feat/answer페이지 modal, padding값 수정

src/components/ui/atoms/dropdown/DropdownMenu.jsx, src/components/ui/atoms/dropdown/DropdownOption.jsx, src/components/ui/atoms/dropdown/DropdownSelect.jsx, src/components/ui/atoms/dropdown/arrow-dropdown/ArrowDropdown.jsx, src/components/ui/atoms/dropdown/context/DropdownProvider.jsx, src/components/ui/atoms/dropdown/hamburger-dropdown/HamburgerDropdown.jsx, src/pages/answer-page/AnswerPage.jsx, src/pages/question-feed-page/QuestFeedPage.jsx
열고 닫는 기능, 콜백 함수 프롭으로 받는 거 Option에 위임.
>
=> ♻️ refactor: 드롭다운 리팩토링

src/components/ui/atoms/badge/BadgeBox.jsx, src/components/ui/molecules/feed-card/FeedCard.jsx, src/components/ui/molecules/feed-card/FeedCardContainer.jsx, src/pages/answer-page/AnswerPage.jsx
1. confirm alert를 map 돌고있는 feedCard안에 넣는 실수를 했다는 것을 이제 알아서 수정함
2. 정말 recoil의 사용이 필요할 듯 보임........ 드릴링이 지구 내핵 뚫고 반대편으로 나감;;;
=> refactor/알럿 여러개 찍혀있는거 코드 수정

README.md
=> 리드미 수정 진행중

README.md
=> 기술스택,협업툴,배포툴 로고 업데이트

README.md
=> read me 시연 gif 추가

README.md
=> readme 위키 링크도 추가
